import type { Metadata } from "next";
import {poppins, openSans} from "./fonts/fonts";
import "./globals.css";

interface CustomMetadata extends Metadata {
  fonts: {
    poppins: string;
    openSans: string;
  };
}

export const metadata: CustomMetadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  fonts : {
    poppins: poppins.variable,
    openSans: openSans.variable
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} && ${openSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
